set_property SRC_FILE_INFO {cfile:E:/Study_Project/FPGA_Competition/Workplace_Vivado/i2c_MCP4725/i2c_MCP4725.srcs/constrs_1/new/i2c_MCP4725.xdc rfile:../../../i2c_MCP4725.srcs/constrs_1/new/i2c_MCP4725.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports clk]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R17 [get_ports rst]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B19 [get_ports scl]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T11 [get_ports sda]
