webtalk_init -webtalk_dir E:/Study_Project/FPGA_Competition/Workplace_Vivado/i2c_MCP4725/i2c_MCP4725.sim/sim_1/behav/xsim/xsim.dir/vtf_i2c_test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Oct  9 20:54:12 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f51c5acd-3b20-4ac4-9b9a-74950eb570ae" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6634f4bb201e4b478c455ddb9b4f0781" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2594 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "100001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "3.44_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14004_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1233054941 -regid "" -xml E:/Study_Project/FPGA_Competition/Workplace_Vivado/i2c_MCP4725/i2c_MCP4725.sim/sim_1/behav/xsim/xsim.dir/vtf_i2c_test_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/Study_Project/FPGA_Competition/Workplace_Vivado/i2c_MCP4725/i2c_MCP4725.sim/sim_1/behav/xsim/xsim.dir/vtf_i2c_test_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/Study_Project/FPGA_Competition/Workplace_Vivado/i2c_MCP4725/i2c_MCP4725.sim/sim_1/behav/xsim/xsim.dir/vtf_i2c_test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
